# keep sorted please, use Edit -> Sort Lines

[versions]
androidCompileSdk = "34"
androidMinSdk = "21"
androidTargetSdk = "34"
accompanist = "0.28.0"
androidx-lifecycle = "2.6.1"
androidx-navigation-compose = "2.5.1"
androidx-tracing = "1.2.0"
coil = "2.2.1"
composeBom = "2024.04.00"
ribs = "0.39.0"
mvicore = "1.2.6"
coroutines = "1.9.0-RC.2"
kotlin = "2.0.20"
junit5 = "5.8.2"
detekt = "1.23.6"
dependencyAnalysis = "1.31.0"

[libraries]
androidx-activity-compose = "androidx.activity:activity-compose:1.7.2"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-arch-core-testing = "androidx.arch.core:core-testing:2.2.0"
androidx-core = "androidx.core:core-ktx:1.12.0"
androidx-core-splashscreen = "androidx.core:core-splashscreen:1.0.1"
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation-compose" }
androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.6.0"
androidx-test-junit = "androidx.test.ext:junit:1.2.0"
androidx-test-rules = "androidx.test:rules:1.6.0"
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
# compose versions are resolved by BOM
compose-animation-core = { module = "androidx.compose.animation:animation-core" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material = { module = "androidx.compose.material3:material3" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-ui = { module = "androidx.compose.ui:ui" }
google-accompanist-systemui = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
google-accompanist-flow = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
google-material = "com.google.android.material:material:1.4.0"
junit = "junit:junit:4.13.2"
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-coroutines-test-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test-jvm", version.ref = "coroutines" }
kotlin-coroutines-rx2 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "coroutines" }
mvicore-base = { module = "com.github.badoo.mvicore:mvicore", version.ref = "mvicore" }
mvicore-android = { module = "com.github.badoo.mvicore:mvicore-android", version.ref = "mvicore" }
mvicore-binder = { module = "com.github.badoo.mvicore:binder", version.ref = "mvicore" }
ribs-base = { module = "com.github.badoo.RIBs:rib-base", version.ref = "ribs" }
ribs-base-test = { module = "com.github.badoo.RIBs:rib-base-test", version.ref = "ribs" }
ribs-base-test-activity = { module = "com.github.badoo.RIBs:rib-base-test-activity", version.ref = "ribs" }
ribs-base-test-rx2 = { module = "com.github.badoo.RIBs:rib-base-test-rx2", version.ref = "ribs" }
ribs-compose = { module = "com.github.badoo.RIBs:rib-compose", version.ref = "ribs" }

rxjava2 = "io.reactivex.rxjava2:rxjava:2.2.21"
rxjava3 = "io.reactivex.rxjava3:rxjava:3.1.5"
rxandroid2 = "io.reactivex.rxjava2:rxandroid:2.1.1"
rxandroid3 = "io.reactivex.rxjava3:rxandroid:3.0.2"
rxrelay2 = "com.jakewharton.rxrelay2:rxrelay:2.1.1"
rxrelay3 = "com.jakewharton.rxrelay3:rxrelay:3.0.1"

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }

plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
plugin-android = "com.android.tools.build:gradle:8.5.2"

detekt-compose = "io.nlopez.compose.rules:detekt:0.1.6"
toolargetool = "com.gu.android:toolargetool:0.3.0"

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
